<?php
// This script and data application were generated by AppGini 5.72
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir = dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");

	handle_maintenance();

	header('Content-type: text/javascript; charset=' . datalist_db_encoding);

	$table_perms = getTablePermissions('addresses');
	if(!$table_perms[0]){ die('// Access denied!'); }

	$mfk = $_GET['mfk'];
	$id = makeSafe($_GET['id']);
	$rnd1 = intval($_GET['rnd1']); if(!$rnd1) $rnd1 = '';

	if(!$mfk){
		die('// No js code available!');
	}

	switch($mfk){

		case 'town':
			if(!$id){
				?>
				$j('#postalCode<?php echo $rnd1; ?>').html('&nbsp;');
				<?php
				break;
			}
			$res = sql("SELECT `town`.`id` as 'id', IF(    CHAR_LENGTH(`countries1`.`country`), CONCAT_WS('',   `countries1`.`country`), '') as 'country', `town`.`idIstat` as 'idIstat', `town`.`town` as 'town', `town`.`district` as 'district', `town`.`region` as 'region', `town`.`prefix` as 'prefix', `town`.`shipCode` as 'shipCode', `town`.`fiscCode` as 'fiscCode', `town`.`inhabitants` as 'inhabitants', `town`.`link` as 'link' FROM `town` LEFT JOIN `countries` as countries1 ON `countries1`.`id`=`town`.`country`  WHERE `town`.`id`='{$id}' limit 1", $eo);
			$row = db_fetch_assoc($res);
			?>
			$j('#postalCode<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(array("\r", "\n"), '', nl2br($row['shipCode']))); ?>&nbsp;');
			<?php
			break;


	}

?>