<?php
// This script and data application were generated by AppGini 5.74
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/addresses.php");
	include("$currDir/addresses_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('addresses');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "addresses";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`addresses`.`id`" => "id",
		"IF(    CHAR_LENGTH(`kinds1`.`name`), CONCAT_WS('',   `kinds1`.`name`), '') /* Tipo */" => "kind",
		"if(CHAR_LENGTH(`addresses`.`address`)>100, concat(left(`addresses`.`address`,100),' ...'), `addresses`.`address`)" => "address",
		"if(CHAR_LENGTH(`addresses`.`houseNumber`)>100, concat(left(`addresses`.`houseNumber`,100),' ...'), `addresses`.`houseNumber`)" => "houseNumber",
		"IF(    CHAR_LENGTH(`countries1`.`code`), CONCAT_WS('',   `countries1`.`code`), '') /* Country Code */" => "country",
		"IF(    CHAR_LENGTH(`countries1`.`country`), CONCAT_WS('',   `countries1`.`country`), '') /* Country Name */" => "country_name",
		"IF(    CHAR_LENGTH(`town1`.`town`), CONCAT_WS('',   `town1`.`town`), '') /* Town */" => "town",
		"IF(    CHAR_LENGTH(`town1`.`shipCode`), CONCAT_WS('',   `town1`.`shipCode`), '') /* PostalCode */" => "postalCode",
		"IF(    CHAR_LENGTH(`town1`.`district`), CONCAT_WS('',   `town1`.`district`), '') /* District */" => "district",
		"IF(    CHAR_LENGTH(`contacts1`.`id`), CONCAT_WS('',   `contacts1`.`id`), '') /* Contact */" => "contact",
		"IF(    CHAR_LENGTH(`companies1`.`id`), CONCAT_WS('',   `companies1`.`id`), '') /* Company */" => "company",
		"`addresses`.`map`" => "map",
		"concat('<i class=\"glyphicon glyphicon-', if(`addresses`.`default`, 'check', 'unchecked'), '\"></i>')" => "default",
		"concat('<i class=\"glyphicon glyphicon-', if(`addresses`.`ship`, 'check', 'unchecked'), '\"></i>')" => "ship"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`addresses`.`id`',
		2 => '`kinds1`.`name`',
		3 => 3,
		4 => 4,
		5 => '`countries1`.`code`',
		6 => '`countries1`.`country`',
		7 => '`town1`.`town`',
		8 => '`town1`.`shipCode`',
		9 => '`town1`.`district`',
		10 => '`contacts1`.`id`',
		11 => '`companies1`.`id`',
		12 => 12,
		13 => '`addresses`.`default`',
		14 => '`addresses`.`ship`'
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`addresses`.`id`" => "id",
		"IF(    CHAR_LENGTH(`kinds1`.`name`), CONCAT_WS('',   `kinds1`.`name`), '') /* Tipo */" => "kind",
		"`addresses`.`address`" => "address",
		"`addresses`.`houseNumber`" => "houseNumber",
		"IF(    CHAR_LENGTH(`countries1`.`code`), CONCAT_WS('',   `countries1`.`code`), '') /* Country Code */" => "country",
		"IF(    CHAR_LENGTH(`countries1`.`country`), CONCAT_WS('',   `countries1`.`country`), '') /* Country Name */" => "country_name",
		"IF(    CHAR_LENGTH(`town1`.`town`), CONCAT_WS('',   `town1`.`town`), '') /* Town */" => "town",
		"IF(    CHAR_LENGTH(`town1`.`shipCode`), CONCAT_WS('',   `town1`.`shipCode`), '') /* PostalCode */" => "postalCode",
		"IF(    CHAR_LENGTH(`town1`.`district`), CONCAT_WS('',   `town1`.`district`), '') /* District */" => "district",
		"IF(    CHAR_LENGTH(`contacts1`.`id`), CONCAT_WS('',   `contacts1`.`id`), '') /* Contact */" => "contact",
		"IF(    CHAR_LENGTH(`companies1`.`id`), CONCAT_WS('',   `companies1`.`id`), '') /* Company */" => "company",
		"`addresses`.`map`" => "map",
		"`addresses`.`default`" => "default",
		"`addresses`.`ship`" => "ship"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`addresses`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`kinds1`.`name`), CONCAT_WS('',   `kinds1`.`name`), '') /* Tipo */" => "Tipo",
		"`addresses`.`address`" => "Address",
		"`addresses`.`houseNumber`" => "HouseNumber",
		"IF(    CHAR_LENGTH(`countries1`.`code`), CONCAT_WS('',   `countries1`.`code`), '') /* Country Code */" => "Country Code",
		"IF(    CHAR_LENGTH(`countries1`.`country`), CONCAT_WS('',   `countries1`.`country`), '') /* Country Name */" => "Country Name",
		"IF(    CHAR_LENGTH(`town1`.`town`), CONCAT_WS('',   `town1`.`town`), '') /* Town */" => "Town",
		"IF(    CHAR_LENGTH(`town1`.`shipCode`), CONCAT_WS('',   `town1`.`shipCode`), '') /* PostalCode */" => "PostalCode",
		"IF(    CHAR_LENGTH(`town1`.`district`), CONCAT_WS('',   `town1`.`district`), '') /* District */" => "District",
		"IF(    CHAR_LENGTH(`contacts1`.`id`), CONCAT_WS('',   `contacts1`.`id`), '') /* Contact */" => "Contact",
		"IF(    CHAR_LENGTH(`companies1`.`id`), CONCAT_WS('',   `companies1`.`id`), '') /* Company */" => "Company",
		"`addresses`.`map`" => "Map",
		"`addresses`.`default`" => "Default",
		"`addresses`.`ship`" => "Ship"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`addresses`.`id`" => "id",
		"IF(    CHAR_LENGTH(`kinds1`.`name`), CONCAT_WS('',   `kinds1`.`name`), '') /* Tipo */" => "kind",
		"`addresses`.`address`" => "Address",
		"`addresses`.`houseNumber`" => "HouseNumber",
		"IF(    CHAR_LENGTH(`countries1`.`code`), CONCAT_WS('',   `countries1`.`code`), '') /* Country Code */" => "country",
		"IF(    CHAR_LENGTH(`countries1`.`country`), CONCAT_WS('',   `countries1`.`country`), '') /* Country Name */" => "country_name",
		"IF(    CHAR_LENGTH(`town1`.`town`), CONCAT_WS('',   `town1`.`town`), '') /* Town */" => "town",
		"IF(    CHAR_LENGTH(`town1`.`shipCode`), CONCAT_WS('',   `town1`.`shipCode`), '') /* PostalCode */" => "postalCode",
		"IF(    CHAR_LENGTH(`town1`.`district`), CONCAT_WS('',   `town1`.`district`), '') /* District */" => "district",
		"IF(    CHAR_LENGTH(`contacts1`.`id`), CONCAT_WS('',   `contacts1`.`id`), '') /* Contact */" => "contact",
		"IF(    CHAR_LENGTH(`companies1`.`id`), CONCAT_WS('',   `companies1`.`id`), '') /* Company */" => "company",
		"`addresses`.`map`" => "map",
		"concat('<i class=\"glyphicon glyphicon-', if(`addresses`.`default`, 'check', 'unchecked'), '\"></i>')" => "default",
		"concat('<i class=\"glyphicon glyphicon-', if(`addresses`.`ship`, 'check', 'unchecked'), '\"></i>')" => "ship"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'kind' => 'Tipo', 'country' => 'Country Code', 'town' => 'Town', 'contact' => 'Contact', 'company' => 'Company');

	$x->QueryFrom = "`addresses` LEFT JOIN `kinds` as kinds1 ON `kinds1`.`code`=`addresses`.`kind` LEFT JOIN `countries` as countries1 ON `countries1`.`id`=`addresses`.`country` LEFT JOIN `town` as town1 ON `town1`.`id`=`addresses`.`town` LEFT JOIN `contacts` as contacts1 ON `contacts1`.`id`=`addresses`.`contact` LEFT JOIN `companies` as companies1 ON `companies1`.`id`=`addresses`.`company` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "addresses_view.php";
	$x->RedirectAfterInsert = "addresses_view.php?SelectedID=#ID#";
	$x->TableTitle = "Addresses";
	$x->TableIcon = "resources/table_icons/mail_box.png";
	$x->PrimaryKey = "`addresses`.`id`";

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("Tipo", "Address", "HouseNumber", "Country Code", "Country Name", "Town", "PostalCode", "District", "Default", "Ship");
	$x->ColFieldName = array('kind', 'address', 'houseNumber', 'country', 'country_name', 'town', 'postalCode', 'district', 'default', 'ship');
	$x->ColNumber  = array(2, 3, 4, 5, 6, 7, 8, 9, 13, 14);

	// template paths below are based on the app main directory
	$x->Template = 'templates/addresses_templateTV.html';
	$x->SelectedTemplate = 'templates/addresses_templateTVS.html';
	$x->TemplateDV = 'templates/addresses_templateDV.html';
	$x->TemplateDVP = 'templates/addresses_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `addresses`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='addresses' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `addresses`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='addresses' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`addresses`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: addresses_init
	$render=TRUE;
	if(function_exists('addresses_init')){
		$args=array();
		$render=addresses_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: addresses_header
	$headerCode='';
	if(function_exists('addresses_header')){
		$args=array();
		$headerCode=addresses_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: addresses_footer
	$footerCode='';
	if(function_exists('addresses_footer')){
		$args=array();
		$footerCode=addresses_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>