<?php
// This script and data application were generated by AppGini 5.73
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir = dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");

	handle_maintenance();

	header('Content-type: text/javascript; charset=' . datalist_db_encoding);

	$table_perms = getTablePermissions('companies');
	if(!$table_perms[0]){ die('// Access denied!'); }

	$mfk = $_GET['mfk'];
	$id = makeSafe($_GET['id']);
	$rnd1 = intval($_GET['rnd1']); if(!$rnd1) $rnd1 = '';

	if(!$mfk){
		die('// No js code available!');
	}

	switch($mfk){

		case 'kind':
			if(!$id){
				?>
				$j('#kind_code<?php echo $rnd1; ?>').html('&nbsp;');
				<?php
				break;
			}
			$res = sql("SELECT `kinds`.`entity` as 'entity', `kinds`.`code` as 'code', if(CHAR_LENGTH(`kinds`.`name`)>100, concat(left(`kinds`.`name`,100),' ...'), `kinds`.`name`) as 'name', `kinds`.`value` as 'value', `kinds`.`descriptions` as 'descriptions' FROM `kinds`  WHERE `kinds`.`code`='{$id}' limit 1", $eo);
			$row = db_fetch_assoc($res);
			?>
			$j('#kind_code<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(array("\r", "\n"), '', nl2br($row['code']))); ?>&nbsp;');
			<?php
			break;


	}

?>